// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vikuvqloviqnfufcvkto.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZpa3V2cWxvdmlxbmZ1ZmN2a3RvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjkyNTQ0NTEsImV4cCI6MjA4NDgzMDQ1MX0.Kat_jl4SNkj6Q_YFpGOGOmqJIyKyzQw-3n1dvojDdWI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});